version: '3.9'
services:
  database:
    container_name: fine-postgres
    image: postgres:14-alpine
    volumes:
      - ../log:/root/log:cached
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_DB=postgres
    ports:
      - '5556:5432'
